//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses_Tbl()
        {
            this.CourseToDomain_Tbl = new HashSet<CourseToDomain_Tbl>();
        }
    
        public int courseId { get; set; }
        public string courseName { get; set; }
        public int teacherId { get; set; }
        public int totalHours { get; set; }
        public Nullable<int> routeCode { get; set; }
        public Nullable<int> specializationCode { get; set; }
    
        public virtual Route_Tbl Route_Tbl { get; set; }
        public virtual Specialization_Tbl Specialization_Tbl { get; set; }
        public virtual Teachers_Tbl Teachers_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseToDomain_Tbl> CourseToDomain_Tbl { get; set; }
    }
}
