//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTimes_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseTimes_Tbl()
        {
            this.RegistrationToCourse_Tbl = new HashSet<RegistrationToCourse_Tbl>();
        }
    
        public int courseTimesId { get; set; }
        public int courseCode { get; set; }
        public string dayOfweek { get; set; }
        public System.DateTime beginningTime { get; set; }
        public System.DateTime endTime { get; set; }
        public System.DateTime beginingDate { get; set; }
        public System.DateTime endDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationToCourse_Tbl> RegistrationToCourse_Tbl { get; set; }
    }
}
