//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaHours_Tbl
    {
        public int diplomaHoursId { get; set; }
        public Nullable<int> diplomaId { get; set; }
        public int domainId { get; set; }
        public int specializationId { get; set; }
        public int numberMinHoursRequired { get; set; }
    
        public virtual Diplomas_Tbl Diplomas_Tbl { get; set; }
        public virtual Domains_Tbl Domains_Tbl { get; set; }
        public virtual Specialization_Tbl Specialization_Tbl { get; set; }
    }
}
