//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusesToUsers_Tbl
    {
        public int StatusUserId { get; set; }
        public int userId { get; set; }
        public int statusId { get; set; }
        public Nullable<int> isApproved { get; set; }
    
        public virtual Status_Tbl Status_Tbl { get; set; }
        public virtual Users_Tbl Users_Tbl { get; set; }
    }
}
