//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers_Tbl()
        {
            this.Courses_Tbl = new HashSet<Courses_Tbl>();
        }
    
        public int teacherId { get; set; }
        public int userId { get; set; }
        public Nullable<int> seniority { get; set; }
        public Nullable<System.DateTime> dateStartWork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses_Tbl> Courses_Tbl { get; set; }
        public virtual Users_Tbl Users_Tbl { get; set; }
    }
}
